[package]
name = "bowtie-rust-jsonschema"
version = "0.1.0"
edition = "2021"

[dependencies]
backtrace = "0.3"
jsonschema = "0.41.0"
serde_json = "1.0"
os_info = "3.14.0"
rustc_version_runtime = "0.3.0"

[build-dependencies]
cargo-lock = "11.0"
