[versions]
kotlin = "1.9.22"
json-schema-validator = "0.0.9"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }

[libraries]
json-schema-validator = { group = "io.github.optimumcode", name = "json-schema-validator", version.ref = "json-schema-validator" }
