[versions]
validator = "2024.2"

kotlin = "1.9.23"
build-jdk = "11"

[libraries]
jsv-bom = { module = "io.openapiprocessor:json-schema-validator-bom", version.ref = "validator" }
jsv-validator = { module = "io.openapiprocessor:json-schema-validator" }
io-interfaces = { module = "io.openapiprocessor:io-interfaces" }
io-jackson = { module = "io.openapiprocessor:io-jackson" }

jackson-bom = "com.fasterxml.jackson:jackson-bom:2.17.0"
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind" }
jackson-kotlin = { module = "com.fasterxml.jackson.module:jackson-module-kotlin" }

logback = "ch.qos.logback:logback-classic:1.5.4"

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
