[package]
name = "bowtie-rust-boon"
version = "0.1.0"
edition = "2021"

[dependencies]
boon = "0.6"
serde_json = "1"
os_info = "3.10.0"
rustc_version_runtime = "0.3.0"

[build-dependencies]
cargo-lock = "10.1"
